# Change these first
owner: rounders # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository
assignees:
  - rounders
  - rounders2

sites:
  - name: Rounders
    url: https://www.rounders.ca
  - name: How2ReachUs
    url: https://how2reach.us
  - name: BC Rare Bird Records
    url: https://bcrarebirdrecords.ca
  - name: Alelucia
    url: https://www.alelucia.com
  - name: Roost Dashboard
    url: https://dashboard.roostsolar.com
  - name: Like2Have.it
    url: https://like2have.it
  - name: momocato
    url: https://momocato.com
  - name: NaturesPicsOnline
    url: https://www.naturespicsonline.com
  - name: John Bentley Blog
    url: https://blog.johnbentley.ca
  - name: Vancouver Now & Then
    url: https://vancouvernowandthen.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /up
  logoUrl: https://www.rounders.ca/assets/rlogo.png
  name: Up Time Checks
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/rounders/up

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
